name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build_with_JDK:

    runs-on: ubuntu-latest
    env: TAG=${{ secrets.DOCKERHUB_USERNAME }}/headerchecker:$(date +%s)
    steps:
    - name: CheckOut
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image (JDK)
      run: |
        export TAG=${{ env.TAG }}
        docker build . --file Dockerfile --tag $TAG
        docker push $TAG

    - name: Build the Docker image (GraalVM)
      run: |
        export TAG=${{ env:TAG }}-native
        docker build . --file Dockerfile.native --tag $TAG
        docker push $TAG

  build_with_GraalVM:
    runs-on: ubuntu-latest

    steps:
    - name: CheckOut
      uses: actions/checkout@v4
    
    - name: Build the Docker image for Native Image
      uses: graalvm/setup-graalvm@v1
      with:
          java-version: ${{ var:JavaVersion }}      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Example step
      run: |
      - name: Example step using Gradle plugin # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: gradlew nativeCompile      run:
